data-collection/deploy/deploy-data-collection.yaml
=> add regexp for database name

.github/workflows/shellcheck-scan.yml, data-collection/utils/lint.sh, data-collection/utils/release.sh, data-collection/utils/upload.sh
=> add shellcheck-scan

data-collection/deploy/account-collector.yaml, data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/module-budgets.yaml, data-collection/deploy/module-compute-optimizer.yaml, data-collection/deploy/module-cost-anomaly.yaml, data-collection/deploy/module-cost-explorer-rightsizing.yaml, data-collection/deploy/module-ecs-chargeback.yaml, data-collection/deploy/module-inventory.yaml, data-collection/deploy/module-organization.yaml, data-collection/deploy/module-pricing.yaml, data-collection/deploy/module-rds-usage.yaml, data-collection/deploy/module-transit-gateway.yaml, data-collection/deploy/module-trusted-advisor.yaml, data-collection/utils/lint.sh
=> revert concurncy reservation

data-collection/deploy/module-pricing.yaml
Regenerated the list based on the most recent index file downloaded from the service URL.
=> Fixed Elasticache pricing field list

data-collection/deploy/account-collector.yaml, data-collection/deploy/module-budgets.yaml, data-collection/deploy/module-compute-optimizer.yaml, data-collection/deploy/module-cost-anomaly.yaml, data-collection/deploy/module-ecs-chargeback.yaml, data-collection/deploy/module-inventory.yaml, data-collection/deploy/module-organization.yaml, data-collection/deploy/module-rds-usage.yaml, data-collection/deploy/module-transit-gateway.yaml, data-collection/deploy/module-trusted-advisor.yaml
Enforce regional invocation of STS client
=> Regional sts

data-collection/deploy/account-collector.yaml
=> Refactoring account collector

.github/workflows/security-scan.yml
=> fix checkov

data-collection/deploy/module-budgets.yaml, data-collection/deploy/module-cost-explorer-rightsizing.yaml, data-collection/deploy/module-inventory.yaml, data-collection/deploy/module-rds-usage.yaml
=> make a database variable

data-collection/deploy/account-collector.yaml, data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/deploy-data-read-permissions.yaml, data-collection/deploy/deploy-in-linked-account.yaml, data-collection/deploy/deploy-in-management-account.yaml, data-collection/deploy/module-backup.yaml, data-collection/deploy/module-budgets.yaml, data-collection/deploy/module-compute-optimizer.yaml, data-collection/deploy/module-cost-anomaly.yaml, data-collection/deploy/module-cost-explorer-rightsizing.yaml, data-collection/deploy/module-cost-optimization-hub.yaml, data-collection/deploy/module-ecs-chargeback.yaml, data-collection/deploy/module-inventory.yaml, data-collection/deploy/module-organization.yaml, data-collection/deploy/module-pricing.yaml, data-collection/deploy/module-rds-usage.yaml, data-collection/deploy/module-transit-gateway.yaml, data-collection/deploy/module-trusted-advisor.yaml, data-collection/test/debugstackets.yml, data-collection/test/utils.py
=> refactoring for update

data-collection/README.md, data-collection/deploy/deploy-in-linked-account.yaml, data-collection/deploy/module-inventory.yaml, data-collection/test/test_from_scratch.py, data-collection/test/utils.py
=> Erichre feature

data-collection/utils/release.sh
=> full sync including delete on release

data-collection/deploy/module-inventory.yaml
=> fix counter

data-collection/deploy/module-inventory.yaml, data-collection/deploy/module-pricing.yaml
=> JMESPath for inventory pagination

data-collection/deploy/deploy-data-collection.yaml
=> add glue database dependency

data-collection/deploy/module-compute-optimizer.yaml
=> Allow graviton compute optimizer

data-collection/deploy/module-inventory.yaml, data-collection/deploy/module-pricing.yaml
=> Adjusted EC2 pricing schema to match latest output

data-collection/deploy/module-compute-optimizer.yaml
=> make role names more expicit

data-collection/deploy/deploy-data-collection.yaml
=> explictly fail of Lake Formation

data-collection/deploy/deploy-data-collection.yaml
=> fix title of s3 bucket

data-collection/deploy/deploy-data-collection.yaml
Per updated Glue policy enforcement
=> Updated 2 roles to add glue:TagResource

data-collection/deploy/module-cost-optimization-hub.yaml
=> Fixed hard-coded CO Hub state machine ARN was h

data-collection/deploy/module-organization.yaml, data-collection/test/utils.py
=> fix special chars in tags

data-collection/deploy/source/s3_files_migration.py
Added key patterns to identify objects that must not be migrated as part of the data collection upgrade process.
=> Adjusting migration script to skip/remove objects not used in newer data collection stack versions

data-collection/deploy/module-organization.yaml
Freeform tags cause many issues with crawler
=> change org tags to array

data-collection/deploy/module-cost-anomaly.yaml, data-collection/deploy/source/partition_repair_util.py
=> Cost anomaly fix and partition reset utility

data-collection/deploy/module-organization.yaml
=> Dates fix from ydm to ymd ISO

data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/module-compute-optimizer.yaml, data-collection/deploy/module-inventory.yaml, data-collection/deploy/module-pricing.yaml, data-collection/utils/lint.sh
1. Add tables definition via lambda (to prevent the situation when tables are there already)
2. Fix issue with deletion of Compute Optimizer Stack
3. add back the support of cfn-lint for modules that use for:each
4. minor refactoring of create database lambda
=> Add tables to inventory and other fixes

data-collection/deploy/deploy-data-collection.yaml
=> Simplify Policy

data-collection/test/utils.py
=> better errors

data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/module-aws-feeds.yaml
Refactor some Lambda code for AWS News Feeds and use frequent scheduler
=> Refactor some Lambda code for AWS News Feeds and use frequent scheduler

data-collection/deploy/deploy-data-read-permissions.yaml
Adding mention of stack version to ensure the stack set resource is detected as modified.
=> Detect data permissions stack set resource changes

data-collection/README.md, data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/deploy-data-read-permissions.yaml, data-collection/deploy/deploy-in-management-account.yaml, data-collection/deploy/module-license-manager.yaml, data-collection/deploy/module-marketplace-licensing.yaml, data-collection/test/test_from_scratch.py, data-collection/test/utils.py
=> Add license manager

data-collection/deploy/deploy-data-collection.yaml
=> Added Athena Database as output export

data-collection/deploy/module-trusted-advisor.yaml
=> Making TA keys Athena compatible by converting to lowercase

data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/deploy-data-read-permissions.yaml, data-collection/deploy/deploy-in-linked-account.yaml, data-collection/deploy/deploy-in-management-account.yaml
=> set default no avoid breaking update

data-collection/CONTRIBUTING.md, data-collection/deploy/module-health-events.yaml, data-collection/deploy/module-inventory.yaml, data-collection/test/conftest.py, data-collection/test/run-test-from-scratch.sh, data-collection/test/test_from_scratch.py
=> Crawler settings

data-collection/deploy/deploy-in-management-account.yaml, data-collection/deploy/module-compute-optimizer.yaml, data-collection/test/test_from_scratch.py
=> add rds co

data-collection/deploy/module-inventory.yaml
=> fix lambda inventory as Environment breaks crawler

data-collection/deploy/module-budgets.yaml, data-collection/deploy/module-inventory.yaml, data-collection/test/run-test-from-scratch.sh, data-collection/test/test_from_scratch.py, data-collection/test/utils.py
=> Fix lambda data

data-collection/deploy/module-health-events.yaml
=> allow catchup health data on adding new payers

data-collection/deploy/module-health-events.yaml
=> fix health

data-collection/README.md, data-collection/deploy/deploy-in-linked-account.yaml, data-collection/deploy/module-inventory.yaml
Adding inventory collection for DB clusters to fetch data related to Aurora Serverless V1 clusters.
=> Inventory collection for RDS DB Clusters

data-collection/deploy/module-aws-feeds.yaml
=> fix feeds with empty fields

data-collection/deploy/module-cost-anomaly.yaml
=> refactor anomalies

data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/module-cost-anomaly.yaml
Added table
*Issue #, if available:* [189](https://github.com/awslabs/cid-framework/issues/189)
Added table
=> Create cost_anomaly_data table when module is deployed

data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/module-pricing.yaml, data-collection/test/utils.py
* Fix Multi region pricing consistency
* Enhance performance of data pulling
* Add collection of Region/Service map
* Remove Graviton mapping for RDS in favor of Graviton Opportunities Dashobard
=> Refactoring of Pricing Module 

data-collection/deploy/module-inventory.yaml
closes #201 
Increasing the MemorySize parameter of the inventory lambda function
=> increase MemorSize of inventory-lambda

rls/deploy/deploy_cid_rls.yaml
=> security restriciton fixes and lint for RLS

data-collection/deploy/module-budgets.yaml
=> latest default layers include a good boto3 now

data-collection/deploy/module-compute-optimizer.yaml
=> remove pip in CO colleciton

rls/utils/release.sh
=> make linter happier

data-collection/deploy/deploy-data-collection.yaml
=> make license module daily by default

data-collection/deploy/source/step-functions/main-state-machine-v2.json
=> fix older versions of state machines

data-collection/deploy/module-inventory.yaml
In organizations where certain regions are enabled for certain accounts, the collector should not stop if it can't assume role or call services in a region
=> Continue with next region if current one fails

data-collection/deploy/account-collector.yaml, data-collection/deploy/module-budgets.yaml, data-collection/deploy/module-support-cases.yaml, data-collection/test/test_from_scratch.py
=> marke cases and budgets collection more robust

data-collection/deploy/module-budgets.yaml
This update fixes issues with regards to the Costfilter and PlannedBudgetLimits data types.
=> Budgets module costfilter & plannedbudgetlimit data type fix

data-collection/deploy/module-inventory.yaml
=> updated SQl query

data-collection/deploy/account-collector.yaml
=> Fix the error with non-orgs based manual account list

case-summarization/utils/release.sh
=> fix cases release script

data-collection/deploy/module-cost-anomaly.yaml
*Issue #, if available:* https://github.com/awslabs/cid-framework/issues/264
*Description of changes:* Multiple root causes Array 
=> Anomalies : Lambda Code change to  Store full array of root causes

data-collection/deploy/account-collector.yaml
=> Fix for json files

data-collection/utils/release.sh
=> add another copy of yaml files into s3prefix (version)

data-exports/deploy/cur-aggregation.yaml, data-exports/deploy/data-exports-aggregation.yaml, data-exports/utils/release.sh
=> Add files and fix release script for data-exports

data-collection/deploy/deploy-in-management-account.yaml, data-collection/deploy/module-compute-optimizer.yaml, test/test_from_scratch.py
=> adding idle resources

data-exports/deploy/data-exports-aggregation.yaml
=> fix data export updates

data-exports/deploy/data-exports-aggregation.yaml
=> add conditions for data exports

data-collection/deploy/module-compute-optimizer.yaml
https://github.com/aws-samples/aws-cudos-framework-deployment/issues/1093
=> add unTagRole

data-collection/deploy/deploy-in-management-account.yaml, data-collection/deploy/module-compute-optimizer.yaml, test/test_from_scratch.py
This reverts commit afe67696db6b3042ec2ff8838020c9ed36338693.
=> Revert "adding idle resources"

data-collection/deploy/module-health-events.yaml
=> Add additional retry to prevent throttling in Health Events

data-exports/deploy/data-exports-aggregation.yaml
=> allow lf in data exports

data-collection/deploy/module-health-events.yaml
Reverts awslabs/cid-data-collection-framework#309
=> Revert "Hotfix health lookback"

data-collection/deploy/deploy-in-linked-account.yaml, data-collection/deploy/module-trusted-advisor.yaml
Modified the existing TA module to incorporate TA Priority data and created a separate table
=> Added TA Priority data collection and table within TA module

data-exports/deploy/data-exports-aggregation.yaml
=> add a shedule for blocking

data-exports/deploy/data-exports-aggregation.yaml
=> Add carbon exports

data-collection/deploy/module-service-quotas.yaml
=> retrive service limit history from all regons in scope and fix current quotas retrival from quota history

data-collection/deploy/module-aws-feeds.yaml
*Issue #, if available:* This PR fixes #336
*Description of changes:* this change allows to enhance the data collection of AWS News feed to include also the CID RSS Feed.
=> addition of the CID RSS Feed in the data collection

data-exports/README.md
=> Add FAQ on S3 cur for intelligent tiering

data-exports/README.md
*Description of changes:* 
1. updated the read me for Advanced Architecture of Data Exports and explained all the steps (numbers) as depicted in the diagram. 
2. Updated the read me for secondary bucket replication instructions and explained the steps depicted in the diagram
=> updated data-exports readme

data-collection/deploy/deploy-data-collection.yaml, data-collection/deploy/deploy-data-read-permissions.yaml, data-collection/utils/upload.sh
*Issue #, if available:* https://github.com/aws-solutions-library-samples/cloud-intelligence-dashboards-data-collection/issues/344
Added nested stack versions
=> add versioning to nested stacks

data-collection/utils/upload.sh, test/test_from_scratch.py, test/utils.py
=> fix version path for tests

data-collection/deploy/module-inventory.yaml
*Issue #, if available:* https://github.com/aws-solutions-library-samples/cloud-intelligence-dashboards-data-collection/issues/387
=> fix cache for inventory

data-collection/deploy/module-aws-feeds.yaml, data-collection/deploy/module-budgets.yaml, data-collection/deploy/module-cost-anomaly.yaml, data-collection/deploy/module-cost-explorer-rightsizing.yaml, data-collection/deploy/module-ecs-chargeback.yaml, data-collection/deploy/module-health-events.yaml, data-collection/deploy/module-isv-feeds.yaml, data-collection/deploy/module-license-manager.yaml, data-collection/deploy/module-organization.yaml, data-collection/deploy/module-quicksight.yaml, data-collection/deploy/module-rds-usage.yaml, data-collection/deploy/module-reference.yaml, data-collection/deploy/module-resilience-hub.yaml, data-collection/deploy/module-service-quotas.yaml, data-collection/deploy/module-support-cases.yaml, data-collection/deploy/module-transit-gateway.yaml, data-collection/deploy/module-trusted-advisor.yaml, data-collection/deploy/module-workspaces-metrics.yaml
=> fix hive issues

data-collection/deploy/module-trusted-advisor.yaml
Fix: added resource id columns for TA Priority dashboard
=> Fix: added resource id columns for TA Priority dashboard
