aws-solutions-library-samples/cloud-intelligence-dashboards-data-collection

- data-collection/deploy/source/s3_files_migration.py
The migration script is updated with:
- Additional optimisation data object keys prefixes to be adjusted in the existing migration method.
- Adding a new migration method that copies existing objects between 2 different buckets making the same adjustments the existing migration method applied to optimisation data object keys.
Copying data between 2 buckets will support an 'isolated' CID version upgrade process by installing the new version of the data collection template, moving pre-existing data to the new version bucket, and finally uninstalling the previous version of the data collection template.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Updating migration script to consider new object keys and new upgrade process

- data-collection/deploy/deploy-data-collection.yaml
Permit multiple account IDs in CSV format, with each account ID conforming to the correct format for account identifiers (12 digits).
> fix: adjusting ManagementAccountID parameter allowed pattern

- data-collection/deploy/module-compute-optimizer.yaml
Tagging is used for the stack set provisioned in the compute optimizer module.
Deployments of regional bucket replication roles fail for regions other than the one where the data collection stack is being deployed.
The permission iam:TagRole is added to ensure the stack set execution role can tag the roles created by the compute optimizer buckets stack set.
> Fix: adding iam:TagRole permission for Compute Optimizer StackSetExecution role

- data-collection/deploy/account-collector.yaml
Based on the Control Tower issue of setting Lambda concurrency to only 10 by default
> Fail fast account collector if Lambda concurrency is less than 500

- data-collection/deploy/deploy-in-linked-account.yaml
- data-collection/deploy/module-inventory.yaml
The changes in this PR will support the EKS Extended Support Cost Projection dashboard. Changes include:
- Data read permissions stack: Adding permissions to list and describe EKS clusters.
- Inventory module: Adding the table definition, data collection function, and AWS object to provision the infrastructure for the EKS inventory data collector.
> EKS inventory data collection

- data-collection/deploy/account-collector.yaml
- data-collection/deploy/deploy-data-collection.yaml
Allows user to deploy a pre-defined list of accounts in the event they cannot use a payer/orgs
> Initial addition of automatic manual account list mode

- data-collection/deploy/module-health-events.yaml
Health API only has 1 active regional endpoint, this function gets the active region. The region is then used for creating new health client
> Add function to get active health region

- data-collection/deploy/deploy-in-linked-account.yaml
- data-collection/deploy/module-budgets.yaml
This update brings following enhancements
1. To add additional IAM Permissions needed to fetch tags in AWS budgets.
2. Updates to the AWS Lambda function to fetch the tags along with the budgets.
3. This update also addresses the issue #124
> Adding AWS Budgets tag collection and updated IAM permissions

- data-collection/deploy/module-budgets.yaml
This update fixes the error in the AWS Lambda function when there is no budgets found in any accounts for a given payer account.
> AWS Budgets Lambda update

- security-hub/deploy/module-securityhub.yaml
Resource" arn in "ReplicationPolicy" was incorrect and leading to errors while replicating objects to cross account bucket for centralized logging.
Changed "Resource" arn in "ReplicationPolicy" for "ReplicationRole" to "arn:${AWS::Partition}:s3:::${DestinationBucketPrefix}${SendDataToAccountID}-security-hub/${CFDataName}/*"
> Fix the issue with ReplicationPolicy

- data-collection/deploy/module-backup.yaml
`exc["errorMessage"]` fails because exc is not a dictionary.
> Get error message by converting exception to string

- case-summarization/deploy/case-summarization.yaml
> summary: avoid actions summary if there no action

- data-collection/deploy/deploy-in-linked-account.yaml
- data-collection/deploy/module-inventory.yaml
*Issue #, if available:* No Issue
*Description of changes:* This is to Add feature nodegroup inventory to listings within eks service.
> Feature change nodegroup inventory

- data-collection/deploy/account-collector.yaml
- data-collection/deploy/deploy-data-collection.yaml
- data-collection/deploy/module-aws-feeds.yaml
- data-collection/deploy/module-backup.yaml
- data-collection/deploy/module-budgets.yaml
- data-collection/deploy/module-compute-optimizer.yaml
- data-collection/deploy/module-cost-anomaly.yaml
- data-collection/deploy/module-cost-explorer-rightsizing.yaml
- data-collection/deploy/module-ecs-chargeback.yaml
- data-collection/deploy/module-health-events.yaml
- data-collection/deploy/module-inventory.yaml
- data-collection/deploy/module-license-manager.yaml
- data-collection/deploy/module-organization.yaml
- data-collection/deploy/module-pricing.yaml
- data-collection/deploy/module-quicksight.yaml
- data-collection/deploy/module-rds-usage.yaml
- data-collection/deploy/module-service-quotas.yaml
- data-collection/deploy/module-support-cases.yaml
- data-collection/deploy/module-transit-gateway.yaml
- data-collection/deploy/module-trusted-advisor.yaml
> Kms support

- data-exports/deploy/data-exports-aggregation.yaml
Added DeploySourceS3 condition to check for IsSourceAccount and DeployDataExport. Previously the condition only depended on DeployDataExport leading the SourceS3 bucket to be created in destination accounts even if no data export was generated.
> Change condition to deploy SourceS3 bucket

- data-collection/deploy/module-support-cases.yaml
*Description of changes:* increased the support case data collection lambda timeout to 900s 
> fix: set timeout to 900s for the support cases collection lambda

- test/test_from_scratch.py
- test/utils.py
Integration tests was failing because EUC utilization module was not being deployed and also the S3 summary test was waiting for 3000 secs instead of 30 secs
Included the deployment parameter for EUC module and changed the wait time for S3 summary check
> Integration tests fixes

- data-collection/deploy/deploy-data-read-permissions.yaml
- data-collection/deploy/deploy-in-linked-account.yaml
- data-collection/deploy/deploy-in-management-account.yaml
- data-collection/deploy/module-compute-optimizer.yaml
- data-collection/deploy/module-workspaces-metrics.yaml
- data-collection/deploy/source/step-functions/awsfeeds-state-machine-v1.json
- test/test_from_scratch.py
This PR implements a hybrid approach to IAM permissions in the "deploy-in-linked-account" template, replacing wildcard resources with specific ARN patterns where supported by AWS APIs while maintaining necessary wildcards only where required.
- Replaced wildcard (`*`) resources with specific ARN patterns where supported
- Implemented resource-level permissions for EC2, RDS, ECS, WorkSpaces, and other services
- Added namespace conditions for CloudWatch metrics permissions
- Maintained wildcards only for APIs that don't support resource-level permissions
- Added clear documentation explaining each use of wildcards
> deploy-in-linked-account.yaml updated with enhanced IAM security

- data-exports/deploy/cur-aggregation.yaml
- data-exports/deploy/data-exports-aggregation.yaml
Updated `NoncurrentVersionExpirationInDays` and `ExpirationInDays` values to reduce data storage in source and destination buckets in payer/management and data collection accounts respectively.
> Updated S3 lifycycle policy for reduced data storage

- data-collection/deploy/deploy-data-collection.yaml
- data-collection/deploy/module-compute-optimizer.yaml
- data-exports/deploy/cur-aggregation.yaml
- data-exports/deploy/data-exports-aggregation.yaml
- security-hub/deploy/module-securityhub.yaml
This makes sure that S3 buckets with Versioning/Expiration enabled are actually emptied, and that Incomplete uploads do not stick around forever.
I added this to every "AWS::S3::Bucket" but only tested data-exports/deploy/cur-aggregation.yaml (because I'm in the process of removing that bucket)
> Delete incomplete multipart uploads and expired delete markers from S3 Buckets

- data-collection/deploy/module-quicksight.yaml
*Issue #, if available:* https://github.com/aws-solutions-library-samples/cloud-intelligence-dashboards-data-collection/issues/361
Adding boto3 retry for large quicksight groups throttling fault tolerance and Increasing timeout to 15 mins in lambda
> Adding Retry logic and timeout to 15 mins for Quicksight module
